name: nitda_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/Allocation.jpg
    - assets/images/default_profile_pic.jpg
    - assets/images/Enterprise.jpg
    - assets/images/Funding.jpg
    - assets/images/HumanCap.jpg
    - assets/images/Infrastructure.jpg
    - assets/images/Monitoring.jpg
    - assets/images/NITDA_00x500.jpeg
    - assets/images/NITDA_400x400.jpg
    - assets/images/Research.jpg
